export const Flags = [
    { name: 'Andorra', src: 'ad' },
    { name: 'UAE', src: 'ae' },
    { name: 'Afghanistan', src: 'af' },
    { name: 'Antigua and Barbuda', src: 'ag' },
    { name: 'Anguilla', src: 'ai' },
    { name: 'Albania', src: 'al' },
    { name: 'Armenia', src: 'am' },
    { name: 'Angola', src: 'ao' },
    { name: 'Antarctica', src: 'aq' },
    { name: 'Argentina', src: 'ar' },
    { name: 'Austria', src: 'at' },
    { name: 'Australia', src: 'au' },
    { name: 'Aruba', src: 'aw' },
    { name: 'Aland Islands', src: 'ax' },
    { name: 'Azerbaijan', src: 'az' },
    { name: 'Bosnia and Herzegovina', src: 'ba' },
    { name: 'Barbados', src: 'bb' },
    { name: 'Bangladesh', src: 'bd' },
    { name: 'Belgium', src: 'be' },
    { name: 'Burkina Faso', src: 'bf' },
    { name: 'Bulgaria', src: 'bg' },
    { name: 'Bahrain', src: 'bh' },
    { name: 'Burundi', src: 'bi' },
    { name: 'Benin', src: 'bj' },
    { name: 'Bermuda', src: 'bm' },
    { name: 'Brunei Darussalam', src: 'bn' },
    { name: 'Bolivia', src: 'bo' },
    { name: 'Brazil', src: 'br' },
    { name: 'Bahamas', src: 'bs' },
    { name: 'Bhutan', src: 'bt' },
    { name: 'Botswana', src: 'bw' },
    { name: 'Belarus', src: 'by' },
    { name: 'Belize', src: 'bz' },
    { name: 'Canada', src: 'ca' },
    { name: 'DR Congo', src: 'cd' },
    { name: 'Central African Republic', src: 'cf' },
    { name: 'Congo Republic', src: 'cg' },
    { name: 'Switzerland', src: 'ch' },
    { name: `Côte d'Ivoire`, src: 'ci' },
    { name: `Cook Islands`, src: 'ck' },
    { name: `Chile`, src: 'cl' },
    { name: `Cameroon`, src: 'cm' },
    { name: `China`, src: 'cn' },
    { name: `Colombia`, src: 'co' },
    { name: `Costa Rica`, src: 'cr' },
    { name: `Cuba`, src: 'cu' },
    { name: `Cabo Verde`, src: 'cv' },
    { name: `Curaçao`, src: 'cw' },
    { name: `Cyprus`, src: 'cy' },
    { name: `Czech Republic`, src: 'cz' },
    { name: `Germany`, src: 'de' },
    { name: `Djibouti`, src: 'dj' },
    { name: `Denmark`, src: 'dk' },
    { name: `Dominica`, src: 'dm' },
    { name: `Dominican Republic`, src: 'do' },
    { name: `Algeria`, src: 'dz' },
    { name: `Ecuador`, src: 'ec' },
    { name: `Estonia`, src: 'ee' },
    { name: `Egypt`, src: 'eg' },
    { name: `Western Sahara`, src: 'eh' },
    { name: `Eritrea`, src: 'er' },
    { name: `Catalonia`, src: 'es-ct' },
    { name: `Spain`, src: 'es' },
    { name: `Ethiopia`, src: 'et' },
    { name: `Europe`, src: 'eu' },
    { name: `Finland`, src: 'fi' },
    { name: `Fiji`, src: 'fj' },
    { name: `Federated States of Micronesia`, src: 'fm' },
    { name: `Faroe Islands`, src: 'fo' },
    { name: `France`, src: 'fr' },
    { name: `Gabon`, src: 'ga' },
    { name: `England`, src: 'gb-eng' },
    { name: `Northern Ireland`, src: 'gb-nir' },
    { name: `Scotland`, src: 'gb-sct' },
    { name: `Wales`, src: 'gb-wls' },
    { name: `United Kingdom`, src: 'gb' },
    { name: `Grenada`, src: 'gd' },
    { name: `Georgia`, src: 'ge' },
    { name: `Guernsey`, src: 'gg' },
    { name: `Ghana`, src: 'gh' },
    { name: `Gibraltar`, src: 'gi' },
    { name: `Greenland`, src: 'gl' },
    { name: `Gambia`, src: 'gm' },
    { name: `Guinea`, src: 'gn' },
    { name: `Equatorial Guinea`, src: 'gq' },
    { name: `Greece`, src: 'gr' },
    { name: `Guatemala`, src: 'gt' },
    { name: `Guam`, src: 'gu' },
    { name: `Guinea-Bissau`, src: 'gw' },
    { name: `Guyana`, src: 'gy' },
    { name: `Hong Kong`, src: 'hk' },
    { name: `Honduras`, src: 'hn' },
    { name: `Croatia`, src: 'hr' },
    { name: `Haiti`, src: 'ht' },
    { name: `Hungary`, src: 'hu' },
    { name: `Canary Islands`, src: 'ic' },
    { name: `Indonesia`, src: 'id' },
    { name: `Ireland`, src: 'ie' },
    { name: `Israel`, src: 'il' },
    { name: `Isle of Man`, src: 'im' },
    { name: `India`, src: 'in' },
    { name: `Iraq`, src: 'iq' },
    { name: `Iran`, src: 'ir' },
    { name: `Iceland`, src: 'is' },
    { name: `Italy`, src: 'it' },
    { name: `Jamaica`, src: 'jm' },
    { name: `Jordan`, src: 'jo' },
    { name: `Japan`, src: 'jp' },
    { name: `Kenya`, src: 'ke' },
    { name: `Kyrgyzstan`, src: 'kg' },
    { name: `Cambodia`, src: 'kh' },
    { name: `Comoros`, src: 'km' },
    { name: `Saint Kitts and Nevis`, src: 'kn' },
    { name: `North Korea`, src: 'kp' },
    { name: `South Korea`, src: 'kr' },
    { name: `Kuwait`, src: 'kw' },
    { name: `Cayman Islands`, src: 'ky' },
    { name: `Kazakhstan`, src: 'kz' },
    { name: `Laos`, src: 'la' },
    { name: `Lebanon`, src: 'lb' },
    { name: `Saint Lucia`, src: 'lc' },
    { name: `Liechtenstein`, src: 'li' },
    { name: `Sri Lanka`, src: 'lk' },
    { name: `Liberia`, src: 'lr' },
    { name: `Lesotho`, src: 'ls' },
    { name: `Lithuania`, src: 'lt' },
    { name: `Luxembourg`, src: 'lu' },
    { name: `Latvia`, src: 'lv' },
    { name: `Libya`, src: 'ly' },
    { name: `Morocco`, src: 'ma' },
    { name: `Monaco`, src: 'mc' },
    { name: `Moldova`, src: 'md' },
    { name: `Montenegro`, src: 'me' },
    { name: `Madagascar`, src: 'mg' },
    { name: `Marshall Islands`, src: 'mh' },
    { name: `North Macedonia`, src: 'mk' },
    { name: `Mali`, src: 'ml' },
    { name: `Myanmar`, src: 'mm' },
    { name: `Mongolia`, src: 'mn' },
    { name: `Macau`, src: 'mo' },
    { name: `Martinique`, src: 'mq' },
    { name: `Mauritania`, src: 'mr' },
    { name: `Malta`, src: 'mt' },
    { name: `Mauritius`, src: 'mu' },
    { name: `Maldives`, src: 'mv' },
    { name: `Malawi`, src: 'mw' },
    { name: `Mexico`, src: 'mx' },
    { name: `Malaysia`, src: 'my' },
    { name: `Mozambique`, src: 'mz' },
    { name: `Namibia`, src: 'na' },
    { name: `New Caledonia`, src: 'nc' },
    { name: `Niger`, src: 'ne' },
    { name: `Norfolk Island`, src: 'nf' },
    { name: `Nigeria`, src: 'ng' },
    { name: `Nicaragua`, src: 'ni' },
    { name: `Netherlands`, src: 'nl' },
    { name: `Norway`, src: 'no' },
    { name: `Nepal`, src: 'np' },
    { name: `Nauru`, src: 'nr' },
    { name: `Niue`, src: 'nu' },
    { name: `New Zealand`, src: 'nz' },
    { name: `Oman`, src: 'om' },
    { name: `Panama`, src: 'pa' },
    { name: `Peru`, src: 'pe' },
    { name: `French Polynesia`, src: 'pf' },
    { name: `Papua New Guinea`, src: 'pg' },
    { name: `Philippines`, src: 'ph' },
    { name: `Pakistan`, src: 'pk' },
    { name: `Poland`, src: 'pl' },
    { name: `Pitcairn`, src: 'pn' },
    { name: `Puerto Rico`, src: 'pr' },
    { name: `Palestine`, src: 'ps' },
    { name: `Portugal`, src: 'pt' },
    { name: `Palau`, src: 'pw' },
    { name: `Paraguay`, src: 'py' },
    { name: `Qatar`, src: 'qa' },
    { name: `Romania`, src: 'ro' },
    { name: `Serbia`, src: 'rs' },
    { name: `Russia`, src: 'ru' },
    { name: `Rwanda`, src: 'rw' },
    { name: `Saudi Arabia`, src: 'sa' },
    { name: `Solomon Islands`, src: 'sb' },
    { name: `Seychelles`, src: 'sc' },
    { name: `Sudan`, src: 'sd' },
    { name: `Sweden`, src: 'se' },
    { name: `Singapore`, src: 'sg' },
    { name: `Slovenia`, src: 'si' },
    { name: `Slovakia`, src: 'sk' },
    { name: `Sierra Leone`, src: 'sl' },
    { name: `San Marino`, src: 'sm' },
    { name: `Senegal`, src: 'sn' },
    { name: `Somalia`, src: 'so' },
    { name: `Suriname`, src: 'sr' },
    { name: `South Sudan`, src: 'ss' },
    { name: `Sao Tome and Principe`, src: 'st' },
    { name: `El Salvador`, src: 'sv' },
    { name: `Sint Maarten`, src: 'sx' },
    { name: `Syria`, src: 'sy' },
    { name: `Eswatini`, src: 'sz' },
    { name: `Chad`, src: 'td' },
    { name: `Togo`, src: 'tg' },
    { name: `Thailand`, src: 'th' },
    { name: `Tajikistan`, src: 'tj' },
    { name: `Tokelau`, src: 'tk' },
    { name: `Timor-Leste`, src: 'tl' },
    { name: `Turkmenistan`, src: 'tm' },
    { name: `Tunisia`, src: 'tn' },
    { name: `Tonga`, src: 'to' },
    { name: `Turkiye`, src: 'tr' },
    { name: `Trinidad and Tobago`, src: 'tt' },
    { name: `Tuvalu`, src: 'tv' },
    { name: `Taiwan`, src: 'tw' },
    { name: `Tanzania`, src: 'tz' },
    { name: `Ukraine`, src: 'ua' },
    { name: `Uganda`, src: 'ug' },
    { name: `United Nations`, src: 'un' },
    { name: `United States`, src: 'us' },
    { name: `Uruguay`, src: 'uy' },
    { name: `Uzbekistan`, src: 'uz' },
    { name: `Holy See`, src: 'va' },
    { name: `Saint Vincent and the Grenadines`, src: 'vc' },
    { name: `Venezuela`, src: 've' },
    { name: `British Virgin Islands`, src: 'vg' },
    { name: `US Virgin Islands`, src: 'vi' },
    { name: `Vietnam`, src: 'vn' },
    { name: `Vanuatu`, src: 'vu' },
    { name: `Samoa`, src: 'ws' },
    { name: `Kosovo`, src: 'xk' },
    { name: `Yemen`, src: 'ye' },
    { name: `South Africa`, src: 'za' },
    { name: `Zambia`, src: 'zm' },
    { name: `Zimbabwe`, src: 'zw' },
].sort((a, b) => a.name.localeCompare(b.name));