export const Icons = [
    {
        id: '1cBsiNDV7kLcMNnkQPvlH65Kq5j_HBSQs',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_1',
        price: 0,
    },
    {
        id: '1cgPqo6TOIdIBOSKKOfc6bVlVhIlqfYju',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_2',
        price: 0,
    },
    {
        id: '1uSZFtO43GLLp8H4oeaDTlTMhpb5fq93B',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_3',
        price: 10,
    },
    {
        id: '1J_xNo304CSSQu2qbye2JzYf1FATel8x_',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_4',
        price: 10,
    },
    {
        id: '11oP4RJPvB24ue9C1DvWMKy1ldP0GFsEd',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_5',
        price: 10,
    },
    {
        id: '1zFmwx98CruNo9sovuS0VZ8o7lrEkLtNq',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_6',
        price: 10,
    },
    {
        id: '1doOR_0khuRY8GpCAirz7wzOCEuW7Szch',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_7',
        price: 10,
    },
    {
        id: '1JaRyy0xkPO0lvK6wwq4Mes2Tlo0sKKMu',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_8',
        price: 10,
    },
    {
        id: '175J_pn1zhvgOCIk-oDu22hsgZ7rbMTXp',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_9',
        price: 10,
    },
    {
        id: '1V3qqng5UaBvZyVlUjcoPgRYUuYTxZKZ6',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_10',
        price: 10,
    },
    {
        id: '1Wo5c0KIv6bQqw3b-jbqF3ubFCm0xO16P',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_11',
        price: 10,
    },
    {
        id: '1FI6NobCzmPIY4L0oYT7Gcwsu5DgnU4nA',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_12',
        price: 10,
    },
    {
        id: '1JS4efz4nbsnarD8tQzOUd4XNVrt9nYkM',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_13',
        price: 10,
    },
    {
        id: '1y06ZfL4nIX_VChnCCbfLncflm144nmUy',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_14',
        price: 10,
    },
    {
        id: '1ggVLt_w7iK7bM10l-Vwu6CCsNX7z0EYl',
        theme: 'galaxy',
        type: 'female',
        name: 'galaxy_female_15',
        price: 10,
    },
    {
        id: '1ls1HzfLXh3LVxROA8F2Y5kCE36cBD9i-',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_1',
        price: 0,
    },
    {
        id: '1y7_xHyYt6yz6ka1ps-HCbOupTkOWjb0p',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_2',
        price: 0,
    },
    {
        id: '12n9s3rTpf0LpID1cs547aNx0TkrJFkCE',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_3',
        price: 10,
    },
    {
        id: '1nbDLQdbPy4DnDgX7FAbNwk-_x24I6GJO',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_4',
        price: 10,
    },
    {
        id: '1VxIPhAnfvNln73fS_5zKbg4L17WCmF3N',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_5',
        price: 10,
    },
    {
        id: '110xdSM6uCQqkNBxok1EGecyMhHDcPKVh',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_6',
        price: 10,
    },
    {
        id: '1GEQ5TOr0LBxjGW1lw1Ij-FyTfzXM62_P',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_7',
        price: 10,
    },
    {
        id: '1H9Vf5-Cl4a_4tLHSZpOtoSis9d3wYUc9',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_8',
        price: 10,
    },
    {
        id: '1DNEpGi7QJ_ST8aPce8gSkBhwbG1S52rA',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_9',
        price: 10,
    },
    {
        id: '1MVAnQ9rzmB6dmQZnAIN-Fl3SKgLEeU10',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_10',
        price: 10,
    },
    {
        id: '1Jax7jeqbbm5H-B5a1TJYbBdA6zbd16cC',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_11',
        price: 10,
    },
    {
        id: '1Rj5pwkzAkBJtlaLjG4F8p8-cGQrcWN0v',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_12',
        price: 10,
    },
    {
        id: '1H0bL6VVlfPXhwHNI-7BxtTizzLmLXYNJ',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_13',
        price: 10,
    },
    {
        id: '1_XbTrmDo_AAq1sQU44_YlV3WxVKNUqqt',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_14',
        price: 10,
    },
    {
        id: '1U95saIPVyG5qF45XOJrP_bImBA_sZOx5',
        theme: 'galaxy',
        type: 'male',
        name: 'galaxy_male_15',
        price: 10,
    },
    {
        id: '1Vaygdvc-_KLjrBRp2rhF99BozEMmEbHn',
        theme: 'cyberknight',
        type: 'female',
        name: 'cyberknight_female_1',
        price: 35,
    },
    {
        id: '1hFW7Fo8jky9VnDep76Nr-bZ-DCm3WKlq',
        theme: 'cyberknight',
        type: 'female',
        name: 'cyberknight_female_2',
        price: 35,
    },
    {
        id: '1Llwqg0oJ_PaolbJj7hEenM4yqgIEQS7d',
        theme: 'cyberknight',
        type: 'female',
        name: 'cyberknight_female_3',
        price: 35,
    },
    {
        id: '1hw-AG1jsdHfr434BKwuI5b2r_GlEf1gJ',
        theme: 'cyberknight',
        type: 'female',
        name: 'cyberknight_female_4',
        price: 35,
    },
    {
        id: '1I_vQDksg_J9h7ILgg7Y7nKboxr6PSOGH',
        theme: 'cyberknight',
        type: 'female',
        name: 'cyberknight_female_5',
        price: 35,
    },
    {
        id: '1r4cdmdcAtS8JfXabMcXB9c8a3Gu-71YT',
        theme: 'cyberknight',
        type: 'female',
        name: 'cyberknight_female_6',
        price: 35,
    },
    {
        id: '1FlzY1sdb8UsvBS4zEuV5gQIbzpQxRm5j',
        theme: 'cyberknight',
        type: 'female',
        name: 'cyberknight_female_7',
        price: 35,
    },
    {
        id: '1yl-rW1gbB9bx1b2FTTxsQE6M5WoFUNzR',
        theme: 'cyberknight',
        type: 'female',
        name: 'cyberknight_female_8',
        price: 35,
    },
    {
        id: '1PfX-r_UFqa1qph_4uUjGuFyYZHNPT2tN',
        theme: 'cyberknight',
        type: 'female',
        name: 'cyberknight_female_9',
        price: 35,
    },
    {
        id: '1H-ptXxTxclas57CHc3blPPGcq0GqswlN',
        theme: 'cyberknight',
        type: 'male',
        name: 'cyberknight_male_1',
        price: 35,
    },
    {
        id: '1OfrcYzFQbbFwMYOnm0_PJ0Z-XvPJMOEN',
        theme: 'cyberknight',
        type: 'male',
        name: 'cyberknight_male_2',
        price: 35,
    },
    {
        id: '1Tq40rPVzupRX4jDj5nFxmf5uG7ROtRw7',
        theme: 'cyberknight',
        type: 'male',
        name: 'cyberknight_male_3',
        price: 35,
    },
    {
        id: '11Q7zmD2XC6f4S2VOiix3F9vVAQDAcoFR',
        theme: 'cyberknight',
        type: 'male',
        name: 'cyberknight_male_4',
        price: 35,
    },
    {
        id: '1vRXTivKYFUS1zuD29JHdhmnSseU1Jx4D',
        theme: 'cyberknight',
        type: 'male',
        name: 'cyberknight_male_5',
        price: 35,
    },
    {
        id: '1_sJBYGbXmxhY8gq6-CfbC1Ysv8tjubLL',
        theme: 'cyberknight',
        type: 'male',
        name: 'cyberknight_male_6',
        price: 35,
    },
    {
        id: '1KAU7OUNAdepRQhrOXDr352-tK9pCsphD',
        theme: 'cyberknight',
        type: 'male',
        name: 'cyberknight_male_7',
        price: 35,
    },
    {
        id: '1bZTrR40CLcJhMfLwJl7jr07ldKOZxTW7',
        theme: 'cyberknight',
        type: 'male',
        name: 'cyberknight_male_8',
        price: 35,
    },
    {
        id: '1i15KblaO2tOHvyV9nFDJjJv1BBAjRZdn',
        theme: 'cyberknight',
        type: 'male',
        name: 'cyberknight_male_9',
        price: 35,
    },
]